<?php

use Rackage\Model;

/**
 * Setup Pressli Tables
 *
 * Migration: setup_pressli_tables
 * Created: 2026-02-04 10:33:45
 *
 * This migration was auto-generated by comparing your current database
 * schema with the previous migration state.
 */

/**
 * Run the migration (apply changes)
 */
function up()
{
    // Disable foreign key checks to allow table creation in any order
    Model::sql("SET FOREIGN_KEY_CHECKS=0");

    Model::begin();

    try {
    Model::sql("
        CREATE TABLE `api_tokens` (
            `id` int(11) unsigned NOT NULL auto_increment,
            `user_id` int(11) unsigned NOT NULL,
            `name` varchar(100) NOT NULL,
            `token` varchar(64) NOT NULL,
            `times_used` int(11) unsigned NOT NULL DEFAULT 0,
            `last_used` datetime DEFAULT NULL,
            `last_ip` varchar(45) DEFAULT NULL,
            `created_at` datetime DEFAULT NULL,
            `updated_at` datetime DEFAULT NULL,
            PRIMARY KEY (`id`),
            KEY `token_index` (`token`),
            UNIQUE KEY `token_unique` (`token`),
            KEY `user_id_index` (`user_id`),
            CONSTRAINT `fk_tokens_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
    ");

    Model::sql("
        CREATE TABLE `comments` (
            `id` int(11) unsigned NOT NULL auto_increment,
            `post_id` int(11) unsigned NOT NULL,
            `author_name` varchar(255) NOT NULL,
            `author_email` varchar(255) NOT NULL,
            `author_url` varchar(255) DEFAULT NULL,
            `author_ip` varchar(45) NOT NULL,
            `content` text NOT NULL,
            `status` enum('pending','approved','spam') NOT NULL DEFAULT 'pending',
            `parent_id` int(11) unsigned DEFAULT NULL,
            `created_at` datetime DEFAULT NULL,
            `updated_at` datetime DEFAULT NULL,
            `deleted_at` datetime DEFAULT NULL,
            PRIMARY KEY (`id`),
            KEY `author_email_index` (`author_email`),
            KEY `deleted_at_index` (`deleted_at`),
            KEY `idx_post_id_created_at` (`post_id`, `created_at`),
            KEY `idx_status_created_at` (`status`, `created_at`),
            KEY `parent_id_index` (`parent_id`),
            KEY `post_id_index` (`post_id`),
            KEY `status_index` (`status`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
    ");

    Model::sql("
        CREATE TABLE `media` (
            `id` int(11) unsigned NOT NULL auto_increment,
            `filename` varchar(255) NOT NULL,
            `file_path` varchar(500) NOT NULL,
            `file_type` enum('image','video','document','audio','other') NOT NULL DEFAULT 'other',
            `mime_type` varchar(100) NOT NULL,
            `file_size` bigint(20) unsigned NOT NULL,
            `width` int(11) unsigned DEFAULT NULL,
            `height` int(11) unsigned DEFAULT NULL,
            `alt_text` varchar(255) DEFAULT NULL,
            `title` varchar(255) DEFAULT NULL,
            `description` text DEFAULT NULL,
            `author_id` int(11) unsigned NOT NULL,
            `created_at` datetime DEFAULT NULL,
            `updated_at` datetime DEFAULT NULL,
            `deleted_at` datetime DEFAULT NULL,
            PRIMARY KEY (`id`),
            KEY `author_id_index` (`author_id`),
            KEY `deleted_at_index` (`deleted_at`),
            KEY `file_path_index` (`file_path`),
            KEY `file_type_index` (`file_type`),
            CONSTRAINT `fk_media_author_id` FOREIGN KEY (`author_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
    ");

    Model::sql("
        CREATE TABLE `menus` (
            `id` int(11) unsigned NOT NULL auto_increment,
            `name` varchar(100) NOT NULL,
            `slug` varchar(100) NOT NULL,
            `location` varchar(50) DEFAULT NULL,
            `status` enum('active','inactive') NOT NULL DEFAULT 'active',
            `created_at` datetime DEFAULT NULL,
            `updated_at` datetime DEFAULT NULL,
            PRIMARY KEY (`id`),
            UNIQUE KEY `name_unique` (`name`),
            KEY `slug_index` (`slug`),
            UNIQUE KEY `slug_unique` (`slug`),
            KEY `status_index` (`status`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
    ");

    Model::sql("
        CREATE TABLE `menu_items` (
            `id` int(11) unsigned NOT NULL auto_increment,
            `menu_id` int(11) unsigned NOT NULL,
            `parent_id` int(11) unsigned DEFAULT NULL,
            `title` varchar(200) NOT NULL,
            `url` varchar(500) NOT NULL,
            `target` varchar(20) DEFAULT NULL,
            `css_classes` varchar(200) DEFAULT NULL,
            `sort_order` int(11) NOT NULL DEFAULT 0,
            `status` enum('active','inactive') NOT NULL DEFAULT 'active',
            `created_at` datetime DEFAULT NULL,
            `updated_at` datetime DEFAULT NULL,
            PRIMARY KEY (`id`),
            KEY `menu_id_index` (`menu_id`),
            KEY `parent_id_index` (`parent_id`),
            KEY `sort_order_index` (`sort_order`),
            KEY `status_index` (`status`),
            CONSTRAINT `fk_menu_items_menu_id` FOREIGN KEY (`menu_id`) REFERENCES `menus` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
    ");

    Model::sql("
        CREATE TABLE `permissions` (
            `id` int(11) unsigned NOT NULL auto_increment,
            `permission_key` varchar(100) NOT NULL,
            `description` varchar(255) NOT NULL,
            `category` varchar(50) DEFAULT NULL,
            PRIMARY KEY (`id`),
            KEY `category_index` (`category`),
            UNIQUE KEY `permission_key_unique` (`permission_key`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
    ");

    Model::sql("
        CREATE TABLE `plugins` (
            `id` int(11) unsigned NOT NULL auto_increment,
            `slug` varchar(100) NOT NULL,
            `name` varchar(255) NOT NULL,
            `version` varchar(20) NOT NULL,
            `description` text DEFAULT NULL,
            `author` varchar(100) DEFAULT NULL,
            `author_uri` varchar(255) DEFAULT NULL,
            `status` enum('active','inactive') NOT NULL DEFAULT 'inactive',
            `config` longtext DEFAULT NULL,
            `created_at` datetime DEFAULT NULL,
            `updated_at` datetime DEFAULT NULL,
            PRIMARY KEY (`id`),
            UNIQUE KEY `slug_unique` (`slug`),
            KEY `status_index` (`status`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
    ");

    Model::sql("
        CREATE TABLE `posts` (
            `id` int(11) unsigned NOT NULL auto_increment,
            `title` varchar(255) NOT NULL,
            `slug` varchar(255) NOT NULL,
            `content` longtext NOT NULL,
            `excerpt` text DEFAULT NULL,
            `author_id` int(11) unsigned NOT NULL,
            `status` enum('draft','published','scheduled','trash') NOT NULL DEFAULT 'draft',
            `visibility` enum('public','private','password') NOT NULL DEFAULT 'public',
            `password` varchar(255) DEFAULT NULL,
            `featured_image_id` int(11) unsigned DEFAULT NULL,
            `published_at` datetime DEFAULT NULL,
            `comment_count` int(11) unsigned NOT NULL DEFAULT 0,
            `view_count` int(11) unsigned NOT NULL DEFAULT 0,
            `allow_comments` tinyint(1) NOT NULL DEFAULT 1,
            `meta_title` varchar(255) DEFAULT NULL,
            `meta_description` varchar(500) DEFAULT NULL,
            `created_at` datetime DEFAULT NULL,
            `updated_at` datetime DEFAULT NULL,
            `deleted_at` datetime DEFAULT NULL,
            `type` varchar(50) NOT NULL DEFAULT 'post',
            `parent_id` int(11) unsigned DEFAULT NULL,
            `template` varchar(100) DEFAULT NULL,
            `menu_order` int(11) NOT NULL DEFAULT 0,
            PRIMARY KEY (`id`),
            KEY `author_id_index` (`author_id`),
            KEY `deleted_at_index` (`deleted_at`),
            KEY `fk_posts_featured_image_id` (`featured_image_id`),
            KEY `idx_author_id_status` (`author_id`, `status`),
            KEY `idx_parent_id_menu_order` (`parent_id`, `menu_order`),
            KEY `idx_slug_deleted_at` (`slug`, `deleted_at`),
            KEY `idx_type_status_published_at` (`type`, `status`, `published_at`),
            KEY `published_at_index` (`published_at`),
            KEY `slug_index` (`slug`),
            UNIQUE KEY `slug_unique` (`slug`),
            KEY `status_index` (`status`),
            CONSTRAINT `fk_posts_author_id` FOREIGN KEY (`author_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
            CONSTRAINT `fk_posts_featured_image_id` FOREIGN KEY (`featured_image_id`) REFERENCES `media` (`id`) ON DELETE SET NULL ON UPDATE RESTRICT
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
    ");

    Model::sql("
        CREATE TABLE `post_meta` (
            `id` int(11) unsigned NOT NULL auto_increment,
            `post_id` int(11) unsigned NOT NULL,
            `meta_key` varchar(255) NOT NULL,
            `meta_value` longtext DEFAULT NULL,
            PRIMARY KEY (`id`),
            KEY `idx_post_id_meta_key` (`post_id`, `meta_key`),
            KEY `meta_key_index` (`meta_key`),
            KEY `post_id_index` (`post_id`),
            CONSTRAINT `fk_post_meta_post_id` FOREIGN KEY (`post_id`) REFERENCES `posts` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
    ");

    Model::sql("
        CREATE TABLE `post_taxonomies` (
            `id` int(11) unsigned NOT NULL auto_increment,
            `post_id` int(11) unsigned NOT NULL,
            `taxonomy_id` int(11) unsigned NOT NULL,
            PRIMARY KEY (`id`),
            KEY `post_id_index` (`post_id`),
            KEY `taxonomy_id_index` (`taxonomy_id`),
            UNIQUE KEY `unq_post_id_taxonomy_id` (`post_id`, `taxonomy_id`),
            CONSTRAINT `fk_post_taxonomies_post_id` FOREIGN KEY (`post_id`) REFERENCES `posts` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
            CONSTRAINT `fk_post_taxonomies_taxonomy_id` FOREIGN KEY (`taxonomy_id`) REFERENCES `taxonomies` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
    ");

    Model::sql("
        CREATE TABLE `roles` (
            `id` int(11) unsigned NOT NULL auto_increment,
            `name` varchar(50) NOT NULL,
            `description` varchar(255) DEFAULT NULL,
            PRIMARY KEY (`id`),
            UNIQUE KEY `name_unique` (`name`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
    ");

    Model::sql("
        CREATE TABLE `role_permissions` (
            `id` int(11) unsigned NOT NULL auto_increment,
            `role_id` int(11) unsigned NOT NULL,
            `permission_id` int(11) unsigned NOT NULL,
            PRIMARY KEY (`id`),
            KEY `permission_id_index` (`permission_id`),
            KEY `role_id_index` (`role_id`),
            UNIQUE KEY `unq_role_id_permission_id` (`role_id`, `permission_id`),
            CONSTRAINT `fk_role_permissions_permission_id` FOREIGN KEY (`permission_id`) REFERENCES `permissions` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
            CONSTRAINT `fk_role_permissions_role_id` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
    ");

    Model::sql("
        CREATE TABLE `settings` (
            `id` int(11) unsigned NOT NULL auto_increment,
            `name` varchar(100) NOT NULL,
            `value` text DEFAULT NULL,
            `autoload` tinyint(1) NOT NULL DEFAULT 1,
            PRIMARY KEY (`id`),
            KEY `autoload_index` (`autoload`),
            KEY `idx_key_autoload` (`name`, `autoload`),
            UNIQUE KEY `name_unique` (`name`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
    ");

    Model::sql("
        CREATE TABLE `taxonomies` (
            `id` int(11) unsigned NOT NULL auto_increment,
            `name` varchar(200) NOT NULL,
            `slug` varchar(200) NOT NULL,
            `type` enum('category','tag') NOT NULL,
            `description` text DEFAULT NULL,
            `sort_order` int(11) NOT NULL DEFAULT 0,
            `post_count` int(11) unsigned NOT NULL DEFAULT 0,
            `created_at` datetime DEFAULT NULL,
            `updated_at` datetime DEFAULT NULL,
            `deleted_at` datetime DEFAULT NULL,
            `parent_id` int(11) unsigned DEFAULT NULL,
            PRIMARY KEY (`id`),
            KEY `deleted_at_index` (`deleted_at`),
            KEY `parent_id_index` (`parent_id`),
            KEY `slug_index` (`slug`),
            KEY `type_index` (`type`),
            UNIQUE KEY `unq_slug_type_deleted_at` (`slug`, `type`, `deleted_at`),
            CONSTRAINT `fk_taxonomies_parent_id` FOREIGN KEY (`parent_id`) REFERENCES `taxonomies` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
    ");

    Model::sql("
        CREATE TABLE `users` (
            `id` int(11) unsigned NOT NULL auto_increment,
            `username` varchar(60) NOT NULL,
            `email` varchar(255) NOT NULL,
            `password` varchar(255) NOT NULL,
            `first_name` varchar(100) DEFAULT NULL,
            `last_name` varchar(100) DEFAULT NULL,
            `role_id` int(11) unsigned NOT NULL,
            `status` enum('active','inactive','suspended') NOT NULL DEFAULT 'active',
            `avatar` varchar(500) DEFAULT NULL,
            `bio` text DEFAULT NULL,
            `website` varchar(255) DEFAULT NULL,
            `twitter` varchar(100) DEFAULT NULL,
            `facebook` varchar(255) DEFAULT NULL,
            `linkedin` varchar(255) DEFAULT NULL,
            `github` varchar(100) DEFAULT NULL,
            `last_login` datetime DEFAULT NULL,
            `created_at` datetime DEFAULT NULL,
            `updated_at` datetime DEFAULT NULL,
            `deleted_at` datetime DEFAULT NULL,
            `remember_token` varchar(100) DEFAULT NULL,
            `reset_token` varchar(100) DEFAULT NULL,
            `reset_token_expires` datetime DEFAULT NULL,
            `tagline` varchar(255) DEFAULT NULL,
            PRIMARY KEY (`id`),
            UNIQUE KEY `email_unique` (`email`),
            KEY `idx_email_deleted_at` (`email`, `deleted_at`),
            KEY `idx_username_deleted_at` (`username`, `deleted_at`),
            KEY `remember_token_index` (`remember_token`),
            KEY `reset_token_index` (`reset_token`),
            KEY `role_id_index` (`role_id`),
            KEY `status_index` (`status`),
            UNIQUE KEY `username_unique` (`username`),
            CONSTRAINT `fk_users_role_id` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
    ");

        Model::commit();

    } catch (Exception $e) {
        Model::rollback();
        throw $e;

    } finally {
        // Re-enable foreign key checks (always runs, even after exception)
        Model::sql("SET FOREIGN_KEY_CHECKS=1");
    }
}

/**
 * Reverse the migration (rollback changes)
 */
function down()
{
    // Disable foreign key checks to allow table deletion in any order
    Model::sql("SET FOREIGN_KEY_CHECKS=0");

    Model::begin();

    try {
    Model::sql("
        DROP TABLE IF EXISTS `users`
    ");

    Model::sql("
        DROP TABLE IF EXISTS `taxonomies`
    ");

    Model::sql("
        DROP TABLE IF EXISTS `settings`
    ");

    Model::sql("
        DROP TABLE IF EXISTS `role_permissions`
    ");

    Model::sql("
        DROP TABLE IF EXISTS `roles`
    ");

    Model::sql("
        DROP TABLE IF EXISTS `post_taxonomies`
    ");

    Model::sql("
        DROP TABLE IF EXISTS `post_meta`
    ");

    Model::sql("
        DROP TABLE IF EXISTS `posts`
    ");

    Model::sql("
        DROP TABLE IF EXISTS `plugins`
    ");

    Model::sql("
        DROP TABLE IF EXISTS `permissions`
    ");

    Model::sql("
        DROP TABLE IF EXISTS `menu_items`
    ");

    Model::sql("
        DROP TABLE IF EXISTS `menus`
    ");

    Model::sql("
        DROP TABLE IF EXISTS `media`
    ");

    Model::sql("
        DROP TABLE IF EXISTS `comments`
    ");

    Model::sql("
        DROP TABLE IF EXISTS `api_tokens`
    ");

        Model::commit();

    } catch (Exception $e) {
        Model::rollback();
        throw $e;

    } finally {
        // Re-enable foreign key checks (always runs, even after exception)
        Model::sql("SET FOREIGN_KEY_CHECKS=1");
    }
}
